const tokensMovistar = {
    Kénos: {
        background: {value: '#ffffff', type: 'color', description: 'white'},
        backgroundBrand: {value: '#019df5', type: 'color', description: 'movistarBlueDark'},
        appBarBackground: {value: '#fff000', type: 'color', description: 'white'},
        backgroundAlternative: {value: '#f6f6f6', type: 'color', description: 'grey1'},
        backgroundContainer: {value: '#ffffff', type: 'color', description: 'white'},
        backgroundFeedbackBottom: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
        backgroundOverlay: {value: '#31323599', type: 'color', description: 'grey6'},
        backgroundSkeleton: {value: '#f6f6f6', type: 'color', description: 'grey1'},
        backgroundSkeletonInverse: {value: '#008edd', type: 'color', description: 'movistarBlueDark60'},
        badge: {value: '#d73241', type: 'color', description: 'pepper55'},
        border: {value: '#dddddd', type: 'color', description: 'grey3'},
        borderDark: {value: '#86888c', type: 'color', description: 'grey5'},
        borderLight: {value: '#f6f6f6', type: 'color', description: 'grey1'},
        borderSelected: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        buttonDangerBackground: {value: '#ff374a', type: 'color', description: 'pepper'},
        buttonDangerBackgroundHover: {value: '#d73241', type: 'color', description: 'pepper55'},
        buttonDangerBackgroundSelected: {value: '#d73241', type: 'color', description: 'pepper55'},
        buttonLinkBackgroundSelected: {value: '#e6f5fd', type: 'color', description: 'movistarBlue10'},
        buttonLinkBackgroundSelectedInverse: {value: '#ffffff33', type: 'color', description: 'white'},
        buttonPrimaryBackground: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        buttonPrimaryBackgroundHover: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        buttonPrimaryBackgroundInverse: {value: '#ffffff', type: 'color', description: 'white'},
        buttonPrimaryBackgroundSelected: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        buttonPrimaryBackgroundSelectedInverse: {
            value: '#80cef9',
            type: 'color',
            description: 'movistarBlue30',
        },
        buttonSecondaryBackground: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        buttonSecondaryBackgroundSelected: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        buttonSecondaryBorderInverse: {value: '#ffffff', type: 'color', description: 'white'},
        buttonSecondaryBorderSelectedInverse: {
            value: '#80cef9',
            type: 'color',
            description: 'movistarBlue30',
        },
        control: {value: '#dddddd', type: 'color', description: 'grey3'},
        controlActivated: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        controlError: {value: '#ff374a', type: 'color', description: 'pepper'},
        error: {value: '#ff374a', type: 'color', description: 'pepper'},
        feedbackErrorBackground: {value: '#ff374a', type: 'color', description: 'pepper'},
        feedbackInfoBackground: {value: '#313235', type: 'color', description: 'grey6'},
        highlight: {value: '#e63780', type: 'color', description: 'pink'},
        inverse: {value: '#ffffff', type: 'color', description: 'white'},
        iosControlKnob: {value: '#ffffff', type: 'color', description: 'white'},
        loadingBar: {value: '#80cef9', type: 'color', description: 'movistarBlue30'},
        loadingBarBackground: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        neutralHigh: {value: '#313235', type: 'color', description: 'grey6'},
        neutralMedium: {value: '#86888c', type: 'color', description: 'grey5'},
        neutralLow: {value: '#f6f6f6', type: 'color', description: 'grey1'},
        promo: {value: '#a13ea1', type: 'color', description: 'purple'},
        success: {value: '#5cb615', type: 'color', description: 'movistarGreen'},
        textAppBar: {value: '#999999', type: 'color', description: 'grey4'},
        textAppBarSelected: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        textButtonPrimary: {value: '#ffffff', type: 'color', description: 'white'},
        textButtonPrimaryInverse: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        textButtonPrimaryInverseSelected: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        textButtonSecondary: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        textButtonSecondaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
        textButtonSecondaryInverseSelected: {value: '#ffffff', type: 'color', description: 'white'},
        textButtonSecondarySelected: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        textLink: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        textLinkDanger: {value: '#ff374a', type: 'color', description: 'pepper'},
        textLinkSnackbar: {value: '#80cef9', type: 'color', description: 'movistarBlue30'},
        textNavigationBarPrimary: {value: '#ffffff', type: 'color', description: 'white'},
        textNavigationBarSecondary: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
        textNavigationSearchBarHint: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
        textNavigationSearchBarText: {value: '#ffffff', type: 'color', description: 'white'},
        textPrimary: {value: '#313235', type: 'color', description: 'grey6'},
        textPrimaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
        textSecondary: {value: '#86888c', type: 'color', description: 'grey5'},
        textSecondaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
        warning: {value: '#f28d15', type: 'color', description: 'egg'},
        toggleAndroidInactive: {value: '#eeeeee', type: 'color', description: 'grey2'},
        toggleAndroidBackgroundActive: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
        textLinkInverse: {value: '#ffffff', type: 'color', description: 'white'},
        navigationBarBackground: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
        divider: {value: '#eeeeee', type: 'color', description: 'grey2'},
        dividerInverse: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        navigationBarDivider: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
        brand: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
        brandHigh: {value: '#008edd', type: 'color', description: 'movistarBlueDark60'},
        successLow: {value: '#eff8e8', type: 'color', description: 'movistarGreen10'},
        warningLow: {value: '#fef4e8', type: 'color', description: 'egg10'},
        errorLow: {value: '#ffebed', type: 'color', description: 'pepper10'},
        promoLow: {value: '#f6ecf6', type: 'color', description: 'purple10'},
        brandLow: {value: '#e6f5fd', type: 'color', description: 'movistarBlueDark10'},
        promoHigh: {value: '#712b71', type: 'color', description: 'purple70'},
        errorHigh: {value: '#b22634', type: 'color', description: 'pepper70'},
        successHigh: {value: '#407f0f', type: 'color', description: 'movistarGreen70'},
        warningHigh: {value: '#6d3f09', type: 'color', description: 'egg80'},
        skeletonWave: {value: '#dddddd', type: 'color', description: 'grey3'},
        '[DEPRECATED] textAmount': {value: '#24ff00', type: 'color', description: 'change to brand'},
        '[DEPRECATED] textTagActive': {value: '#24ff00', type: 'color', description: 'change to brand'},
        '[DEPRECATED] tagBackgroundInactive': {
            value: '#24ff00',
            type: 'color',
            description: 'change to neutralLow',
        },
        '[DEPRECATED] textTagInactive': {
            value: '#24ff00',
            type: 'color',
            description: 'change to neutralMedium',
        },
        textLinkDisabled: {value: '#80cef9', type: 'color'},
        Background: {
            backgroundBrand: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
            appBarBackground: {value: '#ffffff', type: 'color', description: 'white'},
            background: {value: '#ffffff', type: 'color', description: 'white'},
            backgroundContainer: {value: '#ffffff', type: 'color', description: 'white'},
            backgroundOverlay: {value: '#31323599', type: 'color', description: 'grey6'},
            backgroundSkeleton: {value: '#f6f6f6', type: 'color', description: 'grey1'},
            backgroundSkeletonInverse: {value: '#008edd', type: 'color', description: 'movistarBlueDark60'},
            navigationBarBackground: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
            backgroundAlternative: {value: '#f6f6f6', type: 'color', description: 'grey1'},
            backgroundFeedbackBottom: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
            skeletonWave: {value: '#dddddd', type: 'color', description: 'grey3'},
            backgroundBrandSecondary: {value: '#0b2739', type: 'color'},
            Special: {
                specialBackgroundBrand: {value: '#019df4', type: 'color'},
                specialBackground100: {value: '#f28d15', type: 'color'},
                specialBackground200: {value: '#5cb615', type: 'color'},
                specialBackground300: {value: '#a13ea1', type: 'color'},
                specialBackground400: {value: '#e63780', type: 'color'},
            },
        },
        Borders: {
            borderLight: {value: '#f6f6f6', type: 'color', description: 'grey1'},
            border: {value: '#dddddd', type: 'color', description: 'grey3'},
            borderDark: {value: '#86888c', type: 'color', description: 'grey5'},
            borderSelected: {value: '#019df4', type: 'color', description: 'movistarBlue'},
        },
        Buttons: {
            buttonDangerBackground: {value: '#ff374a', type: 'color', description: 'pepper'},
            buttonLinkBackgroundSelected: {value: '#e6f5fd', type: 'color', description: 'movistarBlue10'},
            buttonDangerBackgroundHover: {value: '#d73241', type: 'color', description: 'pepper55'},
            buttonDangerBackgroundSelected: {value: '#d73241', type: 'color', description: 'pepper55'},
            buttonPrimaryBackgroundSelected: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
            buttonLinkBackgroundSelectedInverse: {value: '#ffffff33', type: 'color', description: 'white'},
            buttonPrimaryBackground: {value: '#019df4', type: 'color', description: 'movistarBlue'},
            buttonPrimaryBackgroundHover: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
            buttonPrimaryBackgroundInverse: {value: '#ffffff', type: 'color', description: 'white'},
            buttonPrimaryBackgroundSelectedInverse: {
                value: '#80cef9',
                type: 'color',
                description: 'movistarBlue30',
            },
            buttonSecondaryBackground: {value: '#019df4', type: 'color', description: 'movistarBlue'},
            buttonSecondaryBackgroundSelected: {
                value: '#008edd',
                type: 'color',
                description: 'movistarBlue55',
            },
            buttonSecondaryBorderInverse: {value: '#ffffff', type: 'color', description: 'white'},
            buttonSecondaryBorderSelectedInverse: {
                value: '#80cef9',
                type: 'color',
                description: 'movistarBlue30',
            },
            buttonPrimaryBackgroundBrandDark: {value: '#0b2739', type: 'color'},
            buttonPrimaryBackgroundBrandDarkSelected: {value: '#113a54', type: 'color'},
            buttonSecondaryBorderBrandDark: {value: '#0b2739', type: 'color'},
            buttonSecondaryBorderBrandDarkSelected: {value: '#113a54', type: 'color'},
        },
        Global: {
            brand: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
            brandHigh: {value: '#008edd', type: 'color', description: 'movistarBlueDark60'},
            brandLow: {value: '#e6f5fd', type: 'color', description: 'movistarBlueDark10'},
            neutralHigh: {value: '#313235', type: 'color', description: 'grey6'},
            neutralMedium: {value: '#86888c', type: 'color', description: 'grey5'},
            neutralLow: {value: '#f6f6f6', type: 'color', description: 'grey1'},
            inverse: {value: '#ffffff', type: 'color', description: 'white'},
            error: {value: '#ff374a', type: 'color', description: 'pepper'},
            success: {value: '#5cb615', type: 'color', description: 'movistarGreen'},
            warning: {value: '#f28d15', type: 'color', description: 'egg'},
            promo: {value: '#a13ea1', type: 'color', description: 'purple'},
            highlight: {value: '#e63780', type: 'color', description: 'pink'},
            successLow: {value: '#eff8e8', type: 'color', description: 'movistarGreen10'},
            warningLow: {value: '#fef4e8', type: 'color', description: 'egg10'},
            errorLow: {value: '#ffebed', type: 'color', description: 'pepper10'},
            promoLow: {value: '#f6ecf6', type: 'color', description: 'purple10'},
            promoHigh: {value: '#712b71', type: 'color', description: 'purple70'},
            errorHigh: {value: '#b22634', type: 'color', description: 'pepper70'},
            successHigh: {value: '#407f0f', type: 'color', description: 'movistarGreen70'},
            warningHigh: {value: '#6d3f09', type: 'color', description: 'egg80'},
        },
        Texts: {
            Buttons: {
                textButtonPrimary: {value: '#ffffff', type: 'color', description: 'white'},
                textButtonPrimaryInverseSelected: {
                    value: '#019df4',
                    type: 'color',
                    description: 'movistarBlue',
                },
                textButtonPrimaryInverse: {value: '#019df4', type: 'color', description: 'movistarBlue'},
                textLinkInverse: {value: '#ffffff', type: 'color', description: 'white'},
                textButtonSecondarySelected: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
                textButtonSecondary: {value: '#019df4', type: 'color', description: 'movistarBlue'},
                textLinkDisabled: {value: '#80cef9', type: 'color'},
                textButtonSecondaryInverseSelected: {value: '#ffffff', type: 'color', description: 'white'},
                textButtonSecondaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
                textLink: {value: '#019df4', type: 'color', description: 'movistarBlue'},
                textLinkDanger: {value: '#ff374a', type: 'color', description: 'pepper'},
                textLinkSnackbar: {value: '#80cef9', type: 'color', description: 'movistarBlue30'},
            },
            Global: {
                textPrimary: {value: '#313235', type: 'color', description: 'grey6'},
                textPrimaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
                textSecondary: {value: '#86888c', type: 'color', description: 'grey5'},
                textSecondaryInverse: {value: '#ffffff', type: 'color', description: 'white'},
                '[DEPRECATED] textAmount': {value: '#24ff00', type: 'color', description: 'change to brand'},
            },
            'Bar Texts': {
                textNavigationBarPrimary: {value: '#ffffff', type: 'color', description: 'white'},
                textNavigationBarSecondary: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
                textNavigationSearchBarHint: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
                textNavigationSearchBarText: {value: '#ffffff', type: 'color', description: 'white'},
                textAppBar: {value: '#999999', type: 'color', description: 'grey4'},
                textAppBarSelected: {value: '#019df4', type: 'color', description: 'movistarBlue'},
            },
        },
        Feedbacks: {
            badge: {value: '#d73241', type: 'color', description: 'pepper55'},
            feedbackErrorBackground: {value: '#ff374a', type: 'color', description: 'pepper'},
            feedbackInfoBackground: {value: '#313235', type: 'color', description: 'grey6'},
        },
        Divider: {
            dividerInverse: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
            divider: {value: '#eeeeee', type: 'color', description: 'grey2'},
            navigationBarDivider: {value: '#019df4', type: 'color', description: 'movistarBlueDark'},
        },
        Controls: {
            control: {value: '#dddddd', type: 'color', description: 'grey3'},
            controlActivated: {value: '#019df4', type: 'color', description: 'movistarBlue'},
            controlError: {value: '#ff374a', type: 'color', description: 'pepper'},
            toggleAndroidInactive: {value: '#eeeeee', type: 'color', description: 'grey2'},
            toggleAndroidBackgroundActive: {value: '#b3e1fb', type: 'color', description: 'movistarBlue20'},
            iosControlKnob: {value: '#ffffff', type: 'color', description: 'white'},
            loadingBar: {value: '#80cef9', type: 'color', description: 'movistarBlue30'},
            loadingBarBackground: {value: '#008edd', type: 'color', description: 'movistarBlue55'},
        },
    },
    $themes: [],
    $metadata: {tokenSetOrder: ['Kénos']},
};

export default tokensMovistar;
