import {MI_MOVISTAR_SKIN} from '@skins/constants';

import type {GetKnownSkin, KnownSkin} from '@skins/types';

export const palette = {
    egg: '#f28d15',
    egg10: '#fef4e8',
    egg80: '#6d3f09',
    grey1: '#f6f6f6',
    grey2: '#eeeeee',
    grey3: '#dddddd',
    grey4: '#999999',
    grey5: '#86888c',
    grey6: '#313235',
    movistarBlue10: '#e6f5fd',
    movistarBlue20: '#b3e1fb',
    movistarBlue30: '#80cef9',
    movistarBlueArg: '#00a9e0',
    movistarBlueArg55: '#0098d8',
    movistarBlueDark10: '#e6f5fd',
    movistarBlueDarkSecondary: '#0b2739',
    movistarGreenArg: '#5bc500',
    movistarGreenArg10: '#eff8e8',
    movistarGreenArg40: '#ade27f',
    movistarGreenArg60: '#499e00',
    movistarGreenArg70: '#407f0f',
    pepper: '#ff374a',
    pepper10: '#ffebed',
    pepper55: '#d73241',
    pepper70: '#b22634',
    pink: '#e63780',
    purple: '#a13ea1',
    purple10: '#f6ecf6',
    purple70: '#712b71',
    white: '#ffffff',
    highligtLow: '#FFF0F7',
    highlightHigh: '#BF2E6A',
};

export const getAppMiMovistarSkin: GetKnownSkin = () => {
    const skin: KnownSkin = {
        name: MI_MOVISTAR_SKIN,
        colors: {
            appBarBackground: palette.white,
            background: palette.white,
            backgroundContainer: palette.white,
            backgroundBrand: palette.movistarBlueArg,
            backgroundBrandSecondary: palette.movistarBlueDarkSecondary,
            backgroundOverlay: palette.grey6,
            backgroundSkeleton: palette.grey1,
            backgroundSkeletonInverse: palette.movistarBlueArg55,
            backgroundAlternative: palette.grey1,
            backgroundFeedbackBottom: palette.movistarBlueArg,
            navigationBarBackground: palette.movistarBlueArg,
            skeletonWave: palette.grey3,
            border: palette.grey3,
            borderSelected: palette.movistarGreenArg,
            borderLight: palette.grey1,
            borderDark: palette.grey5,
            buttonDangerBackground: palette.pepper,
            buttonDangerBackgroundSelected: palette.pepper55,
            buttonDangerBackgroundHover: palette.pepper55,
            buttonLinkBackgroundSelected: palette.movistarBlue10,
            buttonLinkBackgroundSelectedInverse: palette.white,
            buttonPrimaryBackground: palette.movistarGreenArg,
            buttonPrimaryBackgroundInverse: palette.white,
            buttonPrimaryBackgroundSelected: palette.movistarGreenArg60,
            buttonPrimaryBackgroundSelectedInverse: palette.movistarBlue30,
            buttonPrimaryBackgroundHover: palette.movistarGreenArg60,
            buttonSecondaryBorderInverse: palette.white,
            buttonSecondaryBorderSelectedInverse: palette.movistarBlue30,
            buttonSecondaryBackground: palette.movistarGreenArg,
            buttonSecondaryBackgroundSelected: palette.movistarGreenArg60,
            control: palette.grey3,
            controlActivated: palette.movistarGreenArg,
            controlError: palette.pepper,
            loadingBar: palette.movistarGreenArg,
            loadingBarBackground: palette.movistarGreenArg40,
            toggleAndroidInactive: palette.grey2,
            toggleAndroidBackgroundActive: palette.movistarBlue20,
            iosControlKnob: palette.white,
            divider: palette.grey2,
            dividerInverse: palette.movistarBlueArg55,
            navigationBarDivider: palette.movistarBlueArg,
            badge: palette.pepper55,
            feedbackErrorBackground: palette.pepper,
            feedbackInfoBackground: palette.grey6,
            brand: palette.movistarBlueArg,
            brandHigh: palette.movistarBlueArg55,
            inverse: palette.white,
            neutralHigh: palette.grey6,
            neutralLow: palette.grey1,
            neutralMedium: palette.grey5,
            promo: palette.purple,
            error: palette.pepper,
            highlight: palette.pink,
            highligtLow: palette.highligtLow,
            highlightHigh: palette.highlightHigh,
            success: palette.movistarGreenArg,
            warning: palette.egg,
            textPrimary: palette.grey6,
            textPrimaryInverse: palette.white,
            textSecondary: palette.grey5,
            textSecondaryInverse: palette.white,
            textButtonPrimary: palette.white,
            textButtonPrimaryInverse: palette.movistarBlueArg,
            textButtonPrimaryInverseSelected: palette.movistarBlueArg,
            textButtonSecondary: palette.movistarGreenArg,
            textButtonSecondarySelected: palette.movistarGreenArg60,
            textButtonSecondaryInverse: palette.white,
            textButtonSecondaryInverseSelected: palette.white,
            textLink: palette.movistarBlueArg,
            textLinkInverse: palette.white,
            textLinkDanger: palette.pepper,
            textLinkSnackbar: palette.movistarBlue30,
            textNavigationBarPrimary: palette.white,
            textNavigationBarSecondary: palette.movistarBlue20,
            textNavigationSearchBarHint: palette.movistarBlue20,
            textNavigationSearchBarText: palette.white,
            textAppBar: palette.grey4,
            textAppBarSelected: palette.movistarBlueArg,
            successLow: palette.movistarGreenArg10,
            warningLow: palette.egg10,
            errorLow: palette.pepper10,
            promoLow: palette.purple10,
            brandLow: palette.movistarBlueDark10,
            successHigh: palette.movistarGreenArg70,
            warningHigh: palette.egg80,
            errorHigh: palette.pepper70,
            promoHigh: palette.purple70,

            // Missing properties

            borderLow: palette.grey1,
            borderHigh: palette.grey5,
            buttonSecondaryBorder: '',
            buttonSecondaryBorderSelected: '',
            buttonSecondaryBackgroundHover: '',
            buttonSecondaryBackgroundInverseHover: '',
            neutralMediumInverse: '',
            successHighInverse: '',
            warningHighInverse: '',
            errorHighInverse: '',
            promoHighInverse: '',
            ProgressBarBackground: '',
            buttonSecondaryBackgroundInverseSelected: '',
        },
    };
    return skin;
};
